name: Hourly Sync

on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      ACTION_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout 源代码库 (echoiron/echo-scoop)
        uses: actions/checkout@v2
        with:
          repository: echoiron/echo-scoop
          path: source_repo_echo_scoop
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 复制特定文件到目标仓库
        run: |
          cp source_repo_echo_scoop/bucket/bypass.json .
          cp source_repo_echo_scoop/bucket/eudic.json .
          cp source_repo_echo_scoop/bucket/potplayer.json .
          cp source_repo_echo_scoop/bucket/dingtalk.json  

      - name: Checkout 源代码库 (chawyehsu/dorado)
        uses: actions/checkout@v2
        with:
          repository: chawyehsu/dorado
          path: source_repo_dorado
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 复制特定文件到目标仓库
        run: cp source_repo_dorado/bucket/downkyi.json .

      - name: Checkout 源代码库 (DoveBoy/Apps) 
        uses: actions/checkout@v2
        with:
          repository: DoveBoy/Apps
          path: source_repo_apps
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 复制特定文件到目标仓库 
        run: cp source_repo_apps/bucket/wechat.json .

      - name: Checkout 目标仓库
        uses: actions/checkout@v2
        with:
          repository: SJH555/HelloBucket
          path: target_repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 复制特定文件到目标仓库
        run: |
          mkdir -p target_repo/bucket
          cp bypass.json target_repo/bucket/
          cp eudic.json target_repo/bucket/
          cp potplayer.json target_repo/bucket/
          cp dingtalk.json target_repo/bucket/
          cp downkyi.json target_repo/bucket/
          cp wechat.json target_repo/bucket/
