name: bucket sync

on:
  schedule:
    - cron: '0 0 */2 * *'  # 每隔 48 小时（UTC 时间）运行一次

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      ACTION_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout source repository (echoiron/echo-scoop)
        uses: actions/checkout@v2
        with:
          repository: echoiron/echo-scoop
          path: source_repo_echo_scoop
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy specific files from source repository (echoiron/echo-scoop)
        run: |
          cp source_repo_echo_scoop/bucket/eudic.json .
          cp source_repo_echo_scoop/bucket/dingtalk.json .

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: SJH555/HelloBucket
          path: target_repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy specific files to target repository
        run: |
          mkdir -p target_repo/bucket
          cp eudic.json target_repo/bucket/
          cp dingtalk.json target_repo/bucket/

      - name: Check if there are changes
        run: |
          cd target_repo
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --local user.email "jiahao.song.me@gmail.com"
            git config --local user.name "SJH"
            git add bucket/*
            git commit -m "Synchronize data to the current repository"
            git push --set-upstream origin main
          else
            echo "No changes to commit. Skipping commit and push."
          fi
